### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds exceeded in localhost\trainmodel\word2vec.php on line 23

### ISSUE THREAD

**Issue by Nasidiqi** [donlinglok/C-word2vec-php#1]
I am using this code  with my website running  on localhost. i copied the code and just changed the input file . 

i ran this code on localhost and received this error.  what to do ?

**Comment by sencere** [comment]
It depends how big your text you trying to train is. Whats happening in your case is, that your running out of execution time for php scripts, which is set in the php.ini. Or just create a 

phpinfo.php file
```php
<?php
phpinfo();
``` 
Solution
1) Your text file you are trying to train is not huge. Then just increase the execution time
```php
set_time_limit(300);
``` 
2) You have a huge text file
Train outside php
```php
cd google-word2vec-trunk && ./word2vec  -train google-word2vec-trunk/YOURTRAINFILE.txt -output YOURVECTORFILE.bin  -cbow 1 -size 500 -window 10 -negative 10 -hs 0 -sample 1e-5 -threads 40 -binary 1 -iter 3 -min-count 10
```
Happy coding
